### ISSUE TITLE
energy measurement broken in latest dev version with MTS0121_plug (poll)

### ISSUE THREAD

**Issue by Skaronator** [Koenkk/zigbee-herdsman-converters#1985]
Hi,

I'm runing the latest dev version ([this to be specific](https://hub.docker.com/layers/koenkk/zigbee2mqtt/latest-dev/images/sha256-066789e1ce4f9fd6bc9a745e4337b30ee6c58e962ea710914df1fe3c6f9f5ac4?context=explore)) and the energy reporting doesn't seems to work consistent.

I have 5 BlitzWolf SHP13 energy plugs in my zigbee network which support energy measurement via poll and the measurment worked fine until a few days(?) ago. **It looks like that only a single device gets updated correctly now.** All other 4 devices doesn't seem to get updated energy measurements?

I saw the commit that changed the default poll interval to 60 seconds so I configured it back to 30 seconds (later to 15 sec for faster debugging).

This is my current devices config:

```yaml
devices:
  '0x842e14fffe359b2e':
    friendly_name: niklas/plug/pc
    measurement_poll_interval: 15
  '0x842e14fffe3665fb':
    friendly_name: niklas/plug/monitor
    measurement_poll_interval: 15
  '0x842e14fffe3665eb':
    friendly_name: bathroom/plug/prusa_light
    measurement_poll_interval: 15
```

To quickly debug I switched back to the latest stable version 1.16.2 and everything worked again. Here is how it looks in Home Assistant:
![image](https://user-images.githubusercontent.com/2886913/103182115-1c83ba80-48a9-11eb-8771-8eb6d7a2d995.png)

After that I switched back to the latest dev version and now only a single device (niklas/plug/pc) gets updated every 15 seconds:

![image](https://user-images.githubusercontent.com/2886913/103182198-ef83d780-48a9-11eb-8218-086a7f6ba873.png)

I did enable the debug log but I can only see log entries for the niklas/plug/pc device. So there was not even an attempt to update the energy metrics from the other devices.

I don't know how the internals work in zigbee2mqtt but my guess would be that the poll event loop is buggy and only checks the first device in the device config list?
