### ISSUE TITLE
Cluster 'hvacThermostat' has no attribute '16387' on SPZB0001

### ISSUE THREAD

**Issue by vrabac** [Koenkk/zigbee-herdsman-converters#2083]
When starting zigbee2mqtt I see the following message below. I am not sure if this can be safely ignored or not? I did not saw this message before, started to appear after Pairing SPZB0001

I am running mosquito and zigbee2mqtt in docker, currently without home-assistant as I am in setup phase.
```
eclipse-mosquitto:2.0.4
koenkk/zigbee2mqtt:1.17.0
Adapter hardware: CC2531
Adapter firmware version: CC2531_DEFAULT_20190608
```

zigbee2mqtt configuration
```
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'localhost'
  user: zigbee2mqtt
  password: password
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
devices:
  '0x00158d00045233c8':
    friendly_name: FensterSchlafzimmer
  '0x00158d0002d7e984':
    friendly_name: AqaraSchlafzimmer
  '0xec1bbdfffee4c2d3':
    friendly_name: BlitzWolfSchlafzimmer
  '0x00158d0002d7df56':
    friendly_name: AqaraWohnzimmer
  '0x00158d00032f604e':
    friendly_name: TermostatSchlafzimmer
    debounce: 0.5
  '0x00158d00053d3c08':
    friendly_name: TermostatKinderzimmer
    debounce: 0.5
```

```"model":"SPZB0001"
"vendor":"Eurotronic"}
"genIdentify","hvacThermostat"
"friendly_name":"0x00158d00032f604e"
"model_id":"SPZB0001","network_address":64323
"power_source":"Battery"
"software_build_id":"22190930"
```

```
Zigbee2MQTT:error 2021-01-14 06:39:34: Failed to call 'Bridge' 'onMQTTConnected' (Error: Cluster 'hvacThermostat' has no attribute '16387'
    at Object.getAttribute (/app/node_modules/zigbee-herdsman/dist/zcl/utils.js:84:19)
    at /app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:87:36
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:83:43)
    at /app/lib/extension/bridge.js:512:60
    at Array.map (<anonymous>)
    at Bridge.publishDevices (/app/lib/extension/bridge.js:484:50)
    at Bridge.onMQTTConnected (/app/lib/extension/bridge.js:47:20)
    at async Controller.callExtensionMethod (/app/lib/controller.js:381:21)
    at async Controller.start (/app/lib/controller.js:167:9))
Zigbee2MQTT:info  2021-01-14 06:39:34: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload 
```
