### ISSUE TITLE
Overwrite max_mireds to 370 for ZS1000204-IN-DE-V1A02

### ISSUE THREAD

**Issue by geigervibe** [Koenkk/zigbee-herdsman-converters#2217]
I bought a Linkind bulb with the model name ZS1000204-IN-DE-V1A02 and registered it via z2m, which was recognized as Linkind ZL1000100-CCT-US-V1A02:
https://www.zigbee2mqtt.io/devices/ZL1000100-CCT-US-V1A02.html

The main problem is that max_mireds should be 370 rather than 500, because at 370 the lamp has already reached the warmest level.
In addition, but less important, the various effects do not differ, they all only flash at the same rate.

**I have installed Home Assistant Supervised (2021.1.4), Mosquitto broker (5.1) and Zigbee2mqtt (1.17.1) are retrofitted as add-ons, the bulbs was integrated via MQTT Discovery.**

The color-temp slider of the bulb has it max at 500 but only upto 370 has an effect (and jumps back to it in hassio (sometimes in z2m-tab expose), if I slide above it) and the developer-tools of hassio show me a max_mireds of 500.

Now I've tried to integrate the bulbs in hassio manually with the additions:
min_mireds: 153
max_mireds: 370
If the bulbs was still integrated, the settings were ineffective even after a restart. If I removed the devices from the integration and switched off auto-discorery, the bulbs did not appear even after a restart. But that's an other issue, which I ignore for now.

I then reversed that and took a closer look at the options of z2m (https://www.zigbee2mqtt.io/information/configuration.html). 'device_options:' was ineffective, especially since I don't know how to bind the parameter to a model, it did not work anyway. 'external_converters:' despite the examples I did not understand at all how I could overwrite the max_mireds value with these.
I even tried to modify the /zigbee2mqtt-1.17.1/node_modules/zigbee-herdsman-converters/devices.js within the container:
`extend: preset.hue.light_onoff_brightness_colortemp_color([153, 370])`
But as soon I restarted the add-on, the setting was back to default.

What amazes me that /share/zigbee2mqtt/database.db apparently recognized the max value correctly (colorTempPhysicalMax":370):

`{"id":7,"type":"Router","ieeeAddr":"0xec1bbdfffeb588bf","nwkAddr":6913,"manufId":4456,"manufName":"lk","powerSource":"Mains (single phase)","modelId":"ZBT-CCTLight-D0106","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":268,"inClusterList":[0,3,4,5,6,8,768,2821,4096,64642],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"ZBT-CCTLight-D0106","manufacturerName":"lk","powerSource":1,"zclVersion":3,"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190509-346","swBuildId":"2.2"}},"lightingColorCtrl":{"attributes":{"colorCapabilities":16,"colorTempPhysicalMin":153,"colorTempPhysicalMax":370,"startUpColorTemperature":65535,"colorTemperature":370}}},"binds":[],"configuredReportings":[],"meta":{}},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":1,"stackVersion":1,"hwVersion":1,"dateCode":"20190509-346","swBuildId":"2.2","zclVersion":3,"interviewCompleted":true,"meta":{"configured":2},"lastSeen":1612722264454}`

**Is there a simple solution here?**

Thanks and regards

**Comment by Koenkk** [comment]
Should already be fixed in the dev branch. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by geigervibe** [comment]
Sorry for my late response, unfortunately had other problems to fix, which are now resolved.

I have now removed the bulb from z2m and hassio, updated z2m to edge and added the bulb again. After a couple of reboots of hassio the bulb was back in hassio as well.

In z2m it looks better now, max_mireds is now 370, but the buttons don't seem to be working, for example at 370 both neutral and warmest are selected. The buttons cool, neutral, warm and warmest do not work in a analogous way.

In hassio everything is unchanged, ie. max_mireds is still 500, but it appears that the mireds parameters are not being transmitted at all. If I look at the mqtt info of the bulb in hassio, there is no mireds parameter here and therefore hassio probably falls back to default 500:

```
availability:
  - topic: zigbee2mqtt/bridge/state
brightness: true
brightness_scale: 254
color_temp: true
command_topic: zigbee2mqtt/zb_linkindlight2/set
device:
  identifiers:
    - zigbee2mqtt_0xec1bbdfffeb588bf
  manufacturer: Linkind
  model: 'Zigbee LED 9W A19 bulb, dimmable & tunable (ZL1000100-CCT-US-V1A02)'
  name: zb_linkindlight2
  sw_version: Zigbee2MQTT 1.17.1-dev
effect: true
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
hs: false
json_attributes_topic: zigbee2mqtt/zb_linkindlight2
name: zb_linkindlight2
schema: json
state_topic: zigbee2mqtt/zb_linkindlight2
unique_id: 0xec1bbdfffeb588bf_light_zigbee2mqtt
xy: false
platform: mqtt
```
