### ISSUE TITLE
Moes TS0601 _TZE200_b6wax7g0 Model TRV BRT-100 

### ISSUE THREAD

**Issue by uspass** [Koenkk/zigbee-herdsman-converters#2937]
There are some issues with this model:

1. system mode
In file zigbee-herdsman-converters/devices/moes.js, line 179 
the next code should be added (which also implies other modifications)
```
.withSystemMode(['heat'], ea.STATE_SET)
```
I know it looks odd, but there are 2 reasons for that. 
First, if we don't have 'heat' only, it will expose all system modes by default. In Home Assistant Lovelace UI it shows all possible modes.
Second, we need ea.STATE_SET (and not ea.STATE) to be able to force get a status 
from the thermostat by sending a mqtt publish to topic: 
'zigbee2mqtt/Termostat_Name/set/system_mode' with payload 'heat'.
It is necessary for the initial status after a system reset.

2. running state
In file zigbee-herdsman-converters/devices/moes.js, line 179 
the code should be modified as following (which also possibly implies other modifications):
```
const allowed = ['idle', 'heat', 'cool', 'heating', 'cooling'];
````
or more general:
```
const allowed = ['idle', 'heat', 'cool', 'heating', 'cooling', 'drying', 'off', 'fan'];
```
and consequently, in file zigbee-herdsman-converters/devices/moes.js, line 179 
the next code should be added:
```
.withRunningState(['idle', 'heating'], ea.STATE)
```
'idle' should be when 'position' is 0, 'heating' should be when different than 0.
This will map the Home Assistant action.

3. BRT-100-TRV supports deadzone
In file zigbee-herdsman-converters/devices/moes.js, line 173
the next code should be added (which also implies other modifications)
```
, tz.moes_thermostat_deadzone_temperature
```
and line 176
```
e.deadzone_temperature(),
```
4. min max temp
In file zigbee-herdsman-converters/devices/moes.js, line 179 
```
withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
```
Sets min_temperature and max_temperature sent to config to 5 and 35 degrees respectively instead of real max, min temperatures. That sets Lovelace UI gauge limits to those values.

I know that zigbee2mqtt is not meant for Home assistant only. 
But I can't find another way to solve all this.

Thanks,
us

**Comment by vladi1234** [comment]
Почему он не подходит так, как сейчас?

`.withPreset(['programming', 'manual', 'temporary_manual', 'holiday']`

**Comment by uspass** [comment]
> Почему он не подходит так, как сейчас?
> 
> `.withPreset(['programming', 'manual', 'temporary_manual', 'holiday']`

English please!

**Comment by vladi1234** [comment]
Why doesn't it fit the way it is now?

`.withPreset(['programming', 'manual', 'temporary_manual', 'holiday']`

**Comment by vladi1234** [comment]
See problem at ZHA

https://github.com/zigpy/zha-device-handlers/pull/1023

**Comment by uspass** [comment]
> 
> 
> Why doesn't it fit the way it is now?
> 
> `.withPreset(['programming', 'manual', 'temporary_manual', 'holiday']`
> 
> Why don't you like this line 179?

In 2. the file name and the line number were wrong. Sorry for that.
Thank you for pointing that out.

us

**Comment by uspass** [comment]
> 
> 
> See problem at ZHA
> 
> [zigpy/zha-device-handlers#1023](https://github.com/zigpy/zha-device-handlers/pull/1023)

I know. This model doesn't work with ZHA. The quirk was wrong.
It works OK with Zigbee2mqtt, though.
I can't use the entity which is created automatically by HA.
To have a proper card in lovelace I had to define my own entity:
```
- platform: mqtt
  name: Termostat Test
  device:
    identifiers: 
      - zigbee2mqtt_0xcc86ecffxxxxxxxx    
    manufacturer: Moes
    model: Thermostatic radiator valve (BRT-100-TRV)
#    name: Thermostat_Baie_Etaj_1
    sw_version: Zigbee2MQTT 1.21.0
  modes: 
    - 'heat'
  mode_state_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  mode_state_template: 'heat'
  action_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  action_template: >-
    {% if value_json.position == 100 %}
      {{ 'heating' }}
    {% elif value_json.position == 0 %}
      {{ 'off' }}
    {% else %}
      {{ 'idle' }}
    {% endif %}
  availability_topic: 'zigbee2mqtt/bridge/state'
  temperature_unit: 'C'
  temp_step: 0.5
  precision: 0.5
  min_temp: 5
  max_temp: 35
  current_temperature_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  current_temperature_template: '{{ value_json.local_temperature }}'
  temperature_command_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1/set/current_heating_setpoint'
  temperature_state_template: '{{ value_json.current_heating_setpoint }}'
  temperature_state_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  hold_modes: 
    - 'programming'
    - 'manual'
    - 'temporary_manual'
    - 'holiday'
  hold_command_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1/set/preset'
  hold_state_template: '{{ value_json.preset }}'
  hold_state_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  json_attributes_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  unique_id: '0xcc86ecffxxxxxxxx_climate_zigbee2mqtt_2'
```

**Comment by vladi1234** [comment]
That is ("_TZE200_b6wax7g0", "TS0601") "Moes TRV BRT-100" Thermostat. It is not compatible with the Tuya !!!

 These are Tuya thermostats:
        ("_TZE200_ckud7u2l", "TS0601"),
        ("_TZE200_ywdxldoj", "TS0601"),
        ("_TZE200_cwnjrr72", "TS0601"),

And that is ("_TZE200_b6wax7g0", "TS0601") "Moes TRV BRT-100" Thermostat.
It is not compatible with the Tuya !!!
It has completely different functions!!!


https://github.com/home-assistant/core/pull/55782
https://github.com/zigpy/zha-device-handlers/pull/1023

**Comment by vladi1234** [comment]
I am not very familiar with Homeassistant and ZHA?

**Comment by uspass** [comment]
> 
> 
> That is ("_TZE200_b6wax7g0", "TS0601") "Moes TRV BRT-100" Thermostat. It is not compatible with the Tuya !!!
> 

It is Tuya.

**Comment by uspass** [comment]
> 
> 
> I am not very familiar with Homeassistant and ZHA?
> 
> I can only say it can't work that way.
> `.withSystemMode(['heat'], ea.STATE_SET).withRunningState(['off', 'idle', 'heating'], ea.STATE)`
> Because "Moes TRV BRT-100" does not have these functions. But it has other functions that can be used for this.

Actually it has the functions. In zigbee-herdsman-converters/lib/exposes.js starting with line 362
```
    withSystemMode(modes, access=a.ALL) {
        assert(!this.endpoint, 'Cannot add feature after adding endpoint');
        const allowed = ['off', 'heat', 'cool', 'auto', 'dry', 'fan_only', 'sleep'];
        modes.forEach((m) => assert(allowed.includes(m)));
        this.features.push(new Enum('system_mode', access, modes).withDescription('Mode of this device'));
        return this;
    }

    withRunningState(modes, access=a.STATE_GET) {
        assert(!this.endpoint, 'Cannot add feature after adding endpoint');
        const allowed = ['idle', 'heat', 'cool'];
        modes.forEach((m) => assert(allowed.includes(m)));
        this.features.push(new Enum('running_state', access, modes).withDescription('The current running state'));
        return this;
    }
```

**Comment by vladi1234** [comment]
> > That is ("_TZE200_b6wax7g0", "TS0601") "Moes TRV BRT-100" Thermostat. It is not compatible with the Tuya !!!
> 
> It is Tuya.

Tuya TRVs just have different families and branding and gie have different functions.

**Comment by uspass** [comment]
> 
> 
> > > That is ("_TZE200_b6wax7g0", "TS0601") "Moes TRV BRT-100" Thermostat. It is not compatible with the Tuya !!!
> > 
> > 
> > It is Tuya.
> 
> Tuya TRVs just have different families and branding and gie have different functions.

When I say it is Tuya I am not speaking about Tuya brand. I am talking about Tuya protocol between MCU and ESP (or whatever communication controller the device uses)

**Comment by uspass** [comment]
A picture worth a thousand words.

![20210905_231416](https://user-images.githubusercontent.com/42880649/132140318-6157ee5d-4e65-41a0-91df-b24017fecc43.jpg)

**Comment by vladi1234** [comment]
> > > That is ("_TZE200_b6wax7g0", "TS0601") "Moes TRV BRT-100" Thermostat. It is not Functions compatible with the Tuya !!!
> > 
> > 
> > It is Tuya.
> 
> Tuya TRVs just have different families and branding and gie have different functions.

**I wrote that is Moes!**
It works with Tuya protocol.

**Comment by vladi1234** [comment]
Do you want to keep playing around with your words?

**Comment by MattWestb** [comment]
All devices that is using tuya DP protocol (most is TS0601) is "tuya devices" and using tuya MCUs.
Z2M have making one "moes" device "group" but all is in the end tuya devices that is manufactured of different factories and being sold under many different names like Moes.

Look on TS004X switches and you is finding them with and without moes name and all is in ground tuya devices only different banded.

Best is moving all Moes devices in the tuya devices than all is the same in the end (tuyas).

And back to topic the BRT-100 is using the same zigbee modules as all tuya TRVs have using before but it have one new MCU / firmware for the MCU and have some different DP commands = normal tuya evolution.

**Comment by MattWestb** [comment]
Little funny thing but its **not** Moes that is doing the TRV its BecaSmart and tuya have it in the there expo https://expo.tuya.com/product/829080 and Moes is baying it as whit label from tuya / BecaSmart.

Sorry but  i finding better going back to the topic with the function is working OK or not and if the code is need being updated or not for this _tuya TRV_.

**Comment by vladi1234** [comment]
I tested Moes BRT-100 with Homessistant + MQTT, works great as it should.

**Comment by OperKH** [comment]
If all OK with this code may be create a PR to include it to the next release?

**Comment by vladi1234** [comment]
This code is wrong.

**Comment by vladi1234** [comment]
> I tested Moes BRT-100 with Homessistant + z2m + MQTT + LOVELACE, works great as it should.

I mean you don't have to do anything anymore and you don't have to create a PR, the whole integration for HA is already done and works great. I tested that too.

https://github.com/Koenkk/zigbee2mqtt.io/blob/master/docs/devices/BRT-100-TRV.md

**Comment by uspass** [comment]
@vladi1234 
When you have tested the BRT-100 in Home assistant, you have seen the following image in Lovelace:

![1](https://user-images.githubusercontent.com/42880649/132961070-51c9b3c3-2800-48bd-903b-6956c60b1b6a.png)
![2](https://user-images.githubusercontent.com/42880649/132961217-0cd49c3d-e79a-4e06-813b-a27510f74cc9.png)

You may notice that you have options to change the mode to auto, heating, cooling, fan_only, off etc. But this device knows only heating. More than that, it even doesn't know 'off'.
Thus, the Lovelace card should look like (based on the card I have made):

![1](https://user-images.githubusercontent.com/42880649/132961172-71ed4764-a413-4092-856f-02987829833d.png)
![3](https://user-images.githubusercontent.com/42880649/132961277-dd17f274-49db-44ad-8f8d-7cd3f1f2fc27.png)

You can see the difference. 
This is what I said in my first post, in point 1 and in the card I have made is set by the lines:
```
  modes: 
    - 'heat'
  mode_state_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  mode_state_template: 'heat'
```
Now about the second point.
Home assistant has a climate property called action. In zigbee-herdsman-converters is called Running state. Action means what is the actual status of the thermostat aka heating, cooling, idle, off etc.
The existent model doesn't take care of this property.
This is why, in the first and second pictures you can see Heat - manual. Heat is heating, but actually, as you can se,e the room temperature is 27 degrees and the target temperature is also 27 degrees. Thus, it should be idle as it is in the third and fourth pictures.
The way to show the right action should be something like:
```  action_topic: 'zigbee2mqtt/Termostat_Baie_Etaj_1'
  action_template: >-
    {% if value_json.position == 100 %}
      {{ 'heating' }}
    {% elif value_json.position == 0 %}
      {{ 'off' }}
    {% else %}
      {{ 'idle' }}
    {% endif %}
```
The third point is a problem indeed. I couldn't figure out when the thermostat reports the deadzone (actually hysteresis). I have monitored the communication and I could not find any dp associated with it.

The fourth point is just a bug.
Say one has a thermostat and manually set the min and max temperature to, say, 10 and 28 degrees respectively.
When creating a card in Lovelace, because of this line:

```
.withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
```
the limits are set to 5 and 35 degrees respectively.
Which is not right.

Cheers,
us

**Comment by vladi1234** [comment]
> There are some issues with this model:
> 
> 1. system mode
>    In file zigbee-herdsman-converters/devices/moes.js, line 179
>    the next code should be added (which also implies other modifications)
> 
> ```
> .withSystemMode(['heat'], ea.STATE_SET)
> ```
> 
> I know it looks odd, but there are 2 reasons for that.
> First, if we don't have 'heat' only, it will expose all system modes by default. In Home Assistant Lovelace UI it shows all possible modes.
> Second, we need ea.STATE_SET (and not ea.STATE) to be able to force get a status
> from the thermostat by sending a mqtt publish to topic:
> 'zigbee2mqtt/Termostat_Name/set/system_mode' with payload 'heat'.
> It is necessary for the initial status after a system reset.
> 
> 1. running state
>    In file zigbee-herdsman-converters/lib/exposes.js, line 372
>    the code should be modified as following (which also possibly implies other modifications):
> 
> ```
> const allowed = ['idle', 'heat', 'cool', 'heating', 'cooling'];
> ```
> 
> or more general:
> 
> ```
> const allowed = ['idle', 'heat', 'cool', 'heating', 'cooling', 'drying', 'off', 'fan'];
> ```
> 
> and consequently, in file zigbee-herdsman-converters/devices/moes.js, line 179
> the next code should be added:
> 
> ```
> .withRunningState(['off', 'idle', 'heating'], ea.STATE)
> ```
> 
> 'heating when position is 100, 'off' when position is 0 and 'idle' in between (25, 50, 75).
> This will map the Home Assistant action.
> 
> 1. BRT-100-TRV supports deadzone
>    In file zigbee-herdsman-converters/devices/moes.js, line 173
>    the next code should be added (which also implies other modifications)
> 
> ```
> , tz.moes_thermostat_deadzone_temperature
> ```
> 
> and line 176
> 
> ```
> e.deadzone_temperature(),
> ```
> 
> 1. min max temp
>    In file zigbee-herdsman-converters/devices/moes.js, line 179
> 
> ```
> withSetpoint('current_heating_setpoint', 5, 35, 0.5, ea.STATE_SET)
> ```
> 
> Sets min_temperature and max_temperature sent to config to 5 and 35 degrees respectively instead of real max, min temperatures. That sets Lovelace UI gauge limits to those values.
> 
> I know that zigbee2mqtt is not meant for Home assistant only.
> But I can't find another way to solve all this.
> 
> Thanks,
> us

Hello @uspass, good to have you back.
I will try to answer all of your questions, but not all of them at once.

question 1). system_mode
It is forbidden to enter functions in z2m that do not exist, because a converter must be built behind each function, which communicates directly with the device!
Therefore you must not enter this line "`.withSystemMode (['heat'], ea.STATE_SET)`".
This means that 'heat' is an additional function that does not exist! You can't build a converter for that!
Therefore the second line also has no meaning "`.withRunningState (['off', 'idle', 'heating'], ea.STATE)`" and that answers the second question.

None of this makes sense!
Above all, you can easily adjust that in the HA without changing the z2m. And without writing any extra code.

![Bildschirmfoto vom 2021-09-12 12-59-06](https://user-images.githubusercontent.com/45510877/132998642-20077640-4ee7-49f9-83c5-b2e01dc32dc3.png)

I tested Moes BRT-100 with Homessistant + z2m + MQTT + LOVELACE, works great as it should.

If you want, I can explain how?

**Comment by uspass** [comment]
@vladi1234 
Thank you for your answer.
I was wrong about .withSystemMode (['heat'], ea.STATE_SET). Should have been .withSystemMode (['heat'], ea.STATE).

Please explain how you did that, as long as you didn't define an entity on platform mqtt.

Thank you,
us

**Comment by vladi1234** [comment]
for `configuration.yaml` I only have this entry MQTT:
```
mqtt:
  discovery: true
  broker: 192.168.178.48  # Remove if you want to use builtin-in MQTT broker
  # birth_message and will_message is not required anymore for Home Assistant 0.113 >=
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
```
So all of my thermostats will be recognized automatically.

Next step you go to **Configuration** -> **Customizations** in the search field you write **climate**, then you see your own thermostats and select the one you have to change.

![Bildschirmfoto vom 2021-09-12 21-22-42](https://user-images.githubusercontent.com/45510877/133000155-4bb6a0fb-4536-4a45-a3ae-423f670117b1.png)

**Then it is deleted that you do not need.**

![Bildschirmfoto vom 2021-09-12 21-23-37](https://user-images.githubusercontent.com/45510877/133000157-02f6383d-3234-4f92-b576-1c396953caeb.png)

Save on computer.
And done!

**Comment by uspass** [comment]
Lovely, I didn't know that.

Thank you,
us

**Comment by vladi1234** [comment]
I am happy for you.

**Comment by vladi1234** [comment]
@uspass  You wrote 
```
BRT-100-TRV supports deadzone
In file zigbee-herdsman-converters / devices / moes.js, line 173
the next code should be added (which also implies other modifications)
, tz.moes_thermostat_deadzone_temperature
and line 176

e.deadzone_temperature (), 
```
Deadzone function cannot be set via z2m, but you can only set dierect on the thermostat. Therefore also makes no sense.

**Comment by OperKH** [comment]
Is it possible to edit scheduler remotely from z2m? There is "Apply" button, but no way to edit it.

**Comment by vladi1234** [comment]
That's right, the button is there, but the z2m scheduler cannot be set. Because that is the standard button with "Apply" button from z2m-fronted. Such a complex converter is hardly possible or almost impossible to build with a standard button. It works, but at least read the settings as text.
That is why the scheduler has to be set directly on the thermostat.

**Comment by vladi1234** [comment]
> Is it possible to edit scheduler remotely from z2m? There is "Apply" button, but no way to edit it.

Hello, I did new PR for schedule today.

With BRT-100-TRV programming mode can now be set directly via fronted.

![Bildschirmfoto vom 2021-11-16 22-08-55](https://user-images.githubusercontent.com/45510877/142257077-9517f4c8-e848-4c3b-92d4-06e531c7e6c1.png)

**Comment by VladNord** [comment]
> **Howto HA adaptation for TRV BRT-100.**
> 
> for `configuration.yaml` I only have this entry MQTT:
> 
> ```
> mqtt:
>   discovery: true
>   broker: 192.168.178.48  # Remove if you want to use builtin-in MQTT broker
>   # birth_message and will_message is not required anymore for Home Assistant 0.113 >=
>   birth_message:
>     topic: 'homeassistant/status'
>     payload: 'online'
>   will_message:
>     topic: 'homeassistant/status'
>     payload: 'offline'
> ```
> 
> So all of my thermostats will be recognized automatically.
> 
> Next step you go to **Configuration** -> **Customizations** in the search field you write **climate**, then you see your own thermostats and select the one you have to change.
> 
> ![Bildschirmfoto vom 2021-09-12 21-22-42](https://user-images.githubusercontent.com/45510877/133000155-4bb6a0fb-4536-4a45-a3ae-423f670117b1.png)
> 
> **Then it is deleted that you do not need.**
> 
> ![Bildschirmfoto vom 2021-09-12 21-23-37](https://user-images.githubusercontent.com/45510877/133000157-02f6383d-3234-4f92-b576-1c396953caeb.png)
> 
> **Save on computer.**
> 
> ![Bildschirmfoto vom 2021-09-12 21-32-21](https://user-images.githubusercontent.com/45510877/133000408-6945d89b-9a97-4d1b-b9c6-815ca5a3eaf1.png)
> 
> **And done!**

Customisation option was removed in 2012.12...

**Comment by vladi1234** [comment]
Of course it is a pity that the useful function has been removed, but that can be changed in other ways.

You have to enter every thermostat that you want to change in the `customize.yaml` file. Xxxxxxxxxx must be changed to name of thermostat.

```
climate.xxxxxxxxxx:
  hvac_modes:
  - heat
  preset_modes:
  - programming
  - manual
  - temporary_manual
  - holiday
  assumed_state: true
climate.xxxxxxxxxxx:
  hvac_modes:
  - heat
  preset_modes:
  - programming
  - manual
  - temporary_manual
  - holiday
  assumed_state: true

```
