### ISSUE TITLE
RTCGQ13LM Body Sensor - false occupancy detected about every 1h 50m

### ISSUE THREAD

**Issue by danielbrunt57** [Koenkk/zigbee-herdsman-converters#5404]
Why are I seeing a false occupancy detected roughly every 1h 50m?
![image](https://user-images.githubusercontent.com/49846893/215305067-2de23a1c-2b0b-46a5-b55d-a2bae9fe0e62.png)

**Comment by danieledwardgeorgehitchcock** [comment]
I'd say this is probably more of an issue to do with the device rather than Z2M - it's difficult to know without looking at the log events around the time that the issue occured...

**Comment by danielbrunt57** [comment]
I have tried the sensor in 2 different locations with both sending false occupancies.  The only thing I can think *might* be triggering it is air flow from my forced air furnace, although the false triggers do not match the patterns of my furnace heat cycles. 
 I have placed it into _solitary confinement_ where there's zero possibility of it seeing any movement, including warm air....

**Comment by danielbrunt57** [comment]
It's still reporting occupancy detected every 2-4 hours despite being inside a closed container.  Not sure if it's a fault with the sensor or what...

**Comment by Koenkk** [comment]
Could you provide the debug log once of this? (false occupancy detected)

See https://www.zigbee2mqtt.io/guide/usage/debug.html on how to enable debug logging.

**Comment by danielbrunt57** [comment]
```
debug 2023-02-14 11:16:00: Received MQTT message on 'homeassistant/sensor/WINDOWS-11-satellite/availability' with data 'online'                                                                             
debug 2023-02-14 11:16:05: Received Zigbee message from 'Body Sensor', type 'attributeReport', cluster 'genPowerCfg', data '{"batteryVoltage":31}' from endpoint 1 with groupID 0                           
info  2023-02-14 11:16:05: MQTT publish: topic 'zigbee2mqtt/Body Sensor', payload '{"battery":100,"detection_interval":120,"device_temperature":20,"linkquality":83,"motion_sensitivity":"medium","occupancy
debug 2023-02-14 11:16:05: Received Zigbee message from 'Body Sensor', type 'attributeReport', cluster 'msOccupancySensing', data '{"occupancy":1}' from endpoint 1 with groupID 0                          
info  2023-02-14 11:16:05: MQTT publish: topic 'zigbee2mqtt/Body Sensor', payload '{"battery":100,"detection_interval":120,"device_temperature":20,"linkquality":83,"motion_sensitivity":"medium","occupancy
info  2023-02-14 11:16:05: MQTT publish: topic 'zigbee2mqtt/Body Sensor', payload '{"battery":100,"detection_interval":120,"device_temperature":20,"linkquality":83,"motion_sensitivity":"medium","no_occupa
info  2023-02-14 11:16:05: MQTT publish: topic 'zigbee2mqtt/Body Sensor', payload '{"battery":100,"detection_interval":120,"device_temperature":20,"linkquality":83,"motion_sensitivity":"medium","no_occupa
debug 2023-02-14 11:16:05: Received Zigbee message from 'Body Sensor', type 'attributeReport', cluster 'aqaraOpple', data '{"247":{"data":[1,33,61,12,3,40,25,4,33,168,19,5,33,13,0,6,36,116,4,0,0,0,8,33,25
```
![image](https://user-images.githubusercontent.com/49846893/218847506-bab1f55f-0408-4868-bb6b-675eb9529451.png)

![image](https://user-images.githubusercontent.com/49846893/218848001-e7f9d5a1-2476-44d0-a3bb-c38386d22e00.png)

**Comment by Otnow** [comment]
@danielbrunt57, could you additionally provide the used _z2m_ version, coordinator firmware version and sensor firmware version (`appVersion` from` database.db` file in _z2m_ data folder)?

**Comment by danielbrunt57** [comment]
``` 
Zigbee2MQTT version: [1.30.1](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.30.1) commit: [unknown](https://github.com/Koenkk/zigbee2mqtt/commit/unknown)
Coordinator type: zStack3x0
Coordinator revision: 20220219
Coordinator IEEE Address; 0x00124b00219ecc03
Frontend version: 0.6.124
```
```
Starting zigbee-herdsman (0.14.89)
```
```
Friendly name:   Body Sensor
Description:
Last seen:    N/A
Availability:  Online
Device type  EndDevice
Zigbee Model:  lumi.motion.agl04
Zigbee Manufacturer:  LUMI
Description:  Aqara high precision motion sensor
Support status:  Supported

IEEE Address:  0x54ef441000397fae
Network address:  0xD5B3
Firmware build date:  20200722
Firmware version:   2019www.
Manufacturer:  [Xiaomi](https://www.zigbee2mqtt.io/supported-devices/#v=Xiaomi)
Model:  [RTCGQ13LM](https://www.zigbee2mqtt.io/devices/RTCGQ13LM.html#xiaomi-rtcgq13lm)
Power:  Battery 100%
Interview completed:  True
```
```
{"id":27,"type":"EndDevice","ieeeAddr":"0x54ef441000397fae","nwkAddr":54707,"manufId":4447,"manufName":"LUMI","powerSource":"Battery","modelId":"lumi.motion.agl04","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":263,"inClusterList":[0,1030,3,1],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.motion.agl04","manufacturerName":"LUMI","powerSource":3,"appVersion":25,"zclVersion":3,"stackVersion":2,"hwVersion":1,"dateCode":"20200722","swBuildId":"2019\u0000www."}},"aqaraOpple":{"attributes":{"247":{"type":"Buffer","data":[1,33,109,12,3,40,25,4,33,168,19,5,33,13,0,6,36,122,4,0,0,0,8,33,25,1,10,33,249,62,12,32,1,100,16,0,101,33,0,0]},"252":0,"258":10,"268":2}},"msOccupancySensing":{"attributes":{"occupancy":1,"pirOToUDelay":120}},"genPowerCfg":{"attributes":{"batteryVoltage":31}}},"binds":[{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00219ecc03","endpointID":1},{"cluster":1030,"type":"endpoint","deviceIeeeAddress":"0x00124b00219ecc03","endpointID":1},{"cluster":2,"type":"endpoint","deviceIeeeAddress":"0x00124b00219ecc03","endpointID":1}],"configuredReportings":[{"cluster":1,"attrId":32,"minRepIntval":3600,"maxRepIntval":62000,"repChange":0},{"cluster":1030,"attrId":0,"minRepIntval":0,"maxRepIntval":"14400","repChange":0}],"meta":{}}},"appVersion":25,"stackVersion":2,"hwVersion":1,"dateCode":"20200722","swBuildId":"2019\u0000www.","zclVersion":3,"interviewCompleted":true,"meta":{"configured":-1582770552},"lastSeen":1676408799905,"defaultSendRequestWhen":"immediate"}
```

**Comment by danielbrunt57** [comment]
Additionally, here are the 10 most recent messages for the body sensor:
```
zigbee2mqtt/Body Sensor
10 most recently received message(s)
Received 10:21:11 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 87
motion_sensitivity: medium
occupancy: false
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3179
Received 11:16:05 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 83
motion_sensitivity: medium
occupancy: false
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3100
Received 11:16:05 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 83
motion_sensitivity: medium
occupancy: true
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3100
Received 11:16:05 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 83
motion_sensitivity: medium
no_occupancy_since:
  undefined: 30
occupancy: true
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3100
Received 11:16:05 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 83
motion_sensitivity: medium
no_occupancy_since:
  undefined: 60
occupancy: true
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3100
Received 11:16:05 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 87
motion_sensitivity: medium
occupancy: true
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3133
Received 11:18:07 AM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 87
motion_sensitivity: medium
occupancy: false
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3133
Received 12:11:16 PM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 80
motion_sensitivity: medium
occupancy: false
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3180
Received 1:06:39 PM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 83
motion_sensitivity: medium
occupancy: false
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3100
Received 1:06:39 PM
QoS: 0
Payload: battery: 100
detection_interval: 120
device_temperature: 20
linkquality: 83
motion_sensitivity: medium
occupancy: false
occupancy_timeout: 120
power_outage_count: 12
state: 'OFF'
temperature: 25
update:
  installed_version: -1
  latest_version: -1
  state: null
update_available: null
voltage: 3120
```
