### ISSUE TITLE
Airam 4713407 reporting not working

### ISSUE THREAD

**Issue by Kryzek** [Koenkk/zigbee-herdsman-converters#700]
Earlier I had this problem with my Airam bulbs spamming my zigbee network to death.

We tried this fix https://github.com/Koenkk/zigbee-herdsman-converters/pull/685 to stop that. Now I noticed that state changes are not getting reported at all from the bulb.

I have my Airam remote  with default groupID of 16387 and I've added bulb in question to same group with
```
advanced:
  report: true

groups:
  '16387':
    retain: false
    friendly_name: remote01
    devices:
      - '0x00158d0001b6beee' (Remote) 
      - '0x00158d0001cded1c' (Bulb)
```
And I can control bulb with remote as intended (ON/OFF/Brightness). But I do not get state reports.

I'm trying with 1.6.0 (commit #b476bc2) and Coordinator (CC2531) firmware version: ```'{"type":"zStack30x","meta":{"transportrev":2,"product":2,"majorrel":2,"minorrel":7,"maintrel":2,"revision":20190425}}'``` if that matters.

And any idea how to manipulate the groupID on remote? I have two remotes and both are using the same groupID (16387).
